---

- name: strategy/synchronize
  block:

    - name: strategy/synchronize > Synchronize
      synchronize:
        src:  "{{ deploy_strategy_synchronize_src }}"
        dest: "{{ deploy_helper.new_release_path }}/"
        rsync_opts: "{{ deploy_strategy_synchronize_rsync_options }}"
