---

- name: task/shell
  block:

    - name: task/shell > "{{ item.options }}" in "{{ item.dir }}"
      shell: >
        {{ item.options }}
      args:
        chdir: "{{ item.dir }}"
      tags: log
