####################################################################
# !!! REMINDER !!!                                                 #
# Don't forget to run `manala up` each time you update this file ! #
####################################################################

manala:
    recipe: elao.app

##########
# System #
##########

system:
    version: 10
    hostname: synchroplayer.vm
    nodejs:
        version: 12

    nginx:
        configs:
            # Gzip
            - file: app_gzip
              template: configs/app_gzip.dev.j2

            # Ssl
            - file: app_ssl.conf
              template: nginx/app_ssl_offloading.conf.j2

            # WebSocket Headers
            - file: app_ws_proxy
              config:
                - proxy_http_version: "1.1"
                - proxy_set_header:   "Upgrade $http_upgrade"
                - proxy_set_header:   'Connection "upgrade"'
                - proxy_set_header:   "Host $host"
                - proxy_set_header:   "X-Real-IP $remote_addr"
                - proxy_set_header:   "X-Forwarded-For $proxy_add_x_forwarded_for"

            # Access Control Headers
            - file: app_access_control
              config:
                - add_header: "Access-Control-Allow-Origin * always"
                - add_header: "Access-Control-Allow-Methods \"GET, POST, PUT, DELETE, OPTIONS\" always"
                - add_header: "Access-Control-Allow-Headers \"Authorization, Content-Type, Accept-Encoding, Cache-Control\" always"
                - add_header: "Access-Control-Allow-Credentials \"true\" always"
                - if ($request_method = OPTIONS):
                  - return: 204

            # Server
            - file: server.conf
              config:
                - server:
                  - server_name: server.synchroplayer.vm
                  - access_log:  /srv/log/server.access.log
                  - error_log:   /srv/log/server.error.log
                  - root:        /srv/app/build
                  - include:     conf.d/app_gzip
                  - include:     conf.d/app_access_control
                  - charset:     UTF-8
                  - location /:
                    - proxy_pass: http://localhost:8001/
                    - include: conf.d/app_ws_proxy
                    - proxy_connect_timeout: 60s
                    - proxy_send_timeout: 60s
                    - proxy_read_timeout: 60s

            # Client
            - file: client.conf
              config:
                - server:
                  - server_name: synchroplayer.vm
                  - access_log:  /srv/log/client.access.log
                  - error_log:   /srv/log/client.error.log
                  - root:        /srv/app/build
                  - include:     conf.d/app_gzip
                  - include:     conf.d/app_access_control
                  - charset:     UTF-8
                  - location /:
                    - try_files: $uri $uri/ /index.html

    supervisor:
        configs:
            - file: server.conf
              programs:
                  synchroplayer:
                      command: node bin/server.js 8001
                      directory: /srv/app
                      stdout_logfile: /srv/log/supervisor.synchroplayer.log
                      autostart: true

    ssh:
        client:
            config:
                - Host tom32i.fr:
                    - User: tom32i
                    - ForwardAgent: true
                - Host deployer.vm:
                    - User: tom32i
                    - ForwardAgent: true
############
# Releases #
############

releases:

  - &release
    mode: production
    repo: git@tom32i.fr:release/synchroplayer.git
    # Release
    release_tasks:
      - shell: make install@production
      - shell: make build
    release_add:
      - bin
      - build
    # Deploy
    deploy_hosts:
      - ssh_host: tom32i.fr
    deploy_dir: /home/tom32i/synchroplayer

  - <<: *release
    mode: staging
    # Deploy
    deploy_hosts:
      - ssh_host: deployer.vm
