release:
    children:

        production:
            hosts:
                localhost@production:
                    ansible_connection: local
                    ansible_python_interpreter: /usr/bin/python3
            vars:
                release_dir: /srv/release/production
                release_git_dir: /srv/app
                release_repo: git@tom32i.fr:release/synchroplayer.git
                release_version: production
                release_tasks:
                  - shell: make install@production
                  - shell: make build
                release_add:
                    - bin
                    - build

        staging:
            hosts:
                localhost@staging:
                    ansible_connection: local
                    ansible_python_interpreter: /usr/bin/python3
            vars:
                release_dir: /srv/release/staging
                release_git_dir: /srv/app
                release_repo: git@tom32i.fr:release/synchroplayer.git
                release_version: staging
                release_tasks:
                  - shell: make install@production
                  - shell: make build
                release_add:
                    - bin
                    - build
