version: '3.8'
services:

  registry:
    image: 'registry:2'
    restart: always
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ${RUNNER_TEMP}/docker-registry
        target: /var/lib/registry

  manala_ci:
    image: manala_ci
    network_mode: 'host'
    command: 'tail -f /dev/null'
    environment:
      XDG_CACHE_HOME: '/docker/.cache/docker'
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCK:-/ssh-agent}
    volumes:
      - type: bind
        consistency: cached
        source: ${GITHUB_WORKSPACE}
        target: /srv/app
      - type: bind
        consistency: delegated
        source: ${GITHUB_WORKSPACE}/.manala
        target: /docker
      - type: bind
        source: ${SSH_AUTH_SOCK:-/home/runner/ssh-agent}
        target: ${SSH_AUTH_SOCK:-/ssh-agent}
