---

manala_accounts_enabled: false
manala_motd_enabled: false
manala_timezone_enabled: false
manala_locales_enabled: false
manala_zsh_enabled: false
manala_environment_enabled: false
manala_apt_enabled: false
manala_ssh_enabled: false
manala_git_enabled: false
manala_ohmyzsh_enabled: false
manala_vim_enabled: false
manala_alternatives_enabled: false
manala_files_enabled: false
manala_nodejs_enabled: false
manala_npm_enabled: false
manala_yarn_enabled: false
manala_php_enabled: false
manala_composer_enabled: false
manala_symfony_cli_enabled: false
manala_nginx_enabled: false
manala_supervisor_enabled: false
manala_ngrok_enabled: false
manala_java_enabled: false
manala_cron_enabled: false
manala_mysql_enabled: false
manala_redis_enabled: false
manala_elasticsearch_enabled: false
manala_influxdb_enabled: false
manala_mongodb_enabled: false
manala_docker_enabled: false
manala_gomplate_enabled: false
