# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version '>= 2.2.10'

Vagrant.configure('2') do |config|

  # Ssh
  config.ssh.forward_agent = true
  config.ssh.insert_key = false
  config.ssh.extra_args = ['-q'] # Quiet mode
  config.ssh.forward_env = ['WORKDIR']

  # Vm
  config.vm.box = 'bento/debian-10'
  config.vm.hostname = 'synchroplayer.vm'
  config.vm.network 'private_network', type: 'dhcp'
  config.vm.define 'development' do |development| end
  config.vm.synced_folder '..', '/srv/app',
    type: 'nfs',
    mount_options: ['tcp', 'nolock', 'actimeo=1']

  # Vm - Virtualbox
  config.vm.provider 'virtualbox' # Force provider
  config.vm.provider :virtualbox do |virtualbox|
    virtualbox.name = 'synchroplayer'
    virtualbox.memory = 2048
    virtualbox.cpus = 1
    virtualbox.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
  end

  # Plugins - Landrush
  config.vagrant.plugins = ['landrush']
  config.landrush.enabled = true
  config.landrush.tld = config.vm.hostname
  config.landrush.guest_redirect_dns = false

  # Vm - Provision - Dotfiles
  for dotfile in ['.gitconfig', '.gitignore']
    if File.exists?(File.join(Dir.home, dotfile)) then
      config.vm.provision dotfile, type: 'file', run: 'always' do |file|
        file.source = '~/' + dotfile
        file.destination = dotfile
      end
    end
  end

  # Vm - Provision - Setup
  config.vm.provision 'setup', type: 'shell' do |setup|
    setup.keep_color = true
    setup.privileged = true
    setup.reset = true
    setup.path = 'vagrant/bin/setup.sh'
  end

  # Vm - Provision - System
  config.vm.provision 'system', type: 'ansible_local' do |system|
    system.provisioning_path = '/vagrant/ansible'
    system.playbook = 'system.yaml'
    system.inventory_path = 'inventories'
    system.become = true
    system.galaxy_role_file = 'roles/system/requirements.yaml'
    system.galaxy_command = 'ansible-galaxy collection install --requirements-file=%{role_file} --force'
    system.tags = ENV['TAGS']
    system.verbose = ENV['VERBOSE'] ? 'vvv' : false
    system.raw_arguments = ENV['DIFF'] ? ['--check', '--diff'] : []
  end

  config.trigger.after :up do |trigger|
    trigger.ruby do |env,machine|
      puts "      \e[32m,\e[0m"
      puts "   \e[31m\\\e[0m  \e[32m:\e[0m  \e[31m/\e[0m     MailHog: http://synchroplayer.vm:8025"
      puts "\e[32m`.\e[0m \e[33m__/ \\__\e[0m \e[32m.'\e[0m"
      puts "\e[31m_ _\e[0m\e[33m\\     /\e[0m\e[31m_ _\e[0m  Supervisor: http://synchroplayer.vm:9001"
      puts "   \e[33m/_   _\\\e[0m"
      puts " \e[32m.'\e[0m  \e[33m\\ /\e[0m  \e[32m`.\e[0m"
      puts "   \e[31m/\e[0m  \e[32m:\e[0m  \e[31m\\\e[0m"
      puts "      \e[32m'\e[0m"
    end
  end

end
