---

# Dirs
release_dir:        ~
release_target_dir: ~

# Git
release_git_dir: ~
release_repo:    ~
release_version: master

# Tasks
release_tasks: []

# Removed
release_removed: []

# Add
release_add: []

# Regex (protocol|host|user|repository)
release_git_url_regex: '^(?P<protocol>https|git)(:\/\/|@)(?P<host>[^\/:]+)[\/:](?P<user>[^\/:]+)\/(?P<repository>.+).git$'
